import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import {
  IonHeader, IonToolbar, IonTitle, IonContent, IonButtons,
  IonBackButton, IonButton, IonIcon, IonList, IonItem,
  IonLabel, IonInput, IonText, IonToggle, IonProgressBar,
  IonToast, IonSelect, IonSelectOption
} from '@ionic/angular/standalone';
import { addIcons } from 'ionicons';
import { saveOutline, closeOutline, addCircleOutline, helpCircleOutline } from 'ionicons/icons';
import { InventoryService } from '../services/inventory.service';
import { InventoryItem } from '../models/inventory.model';
import { NavController, ToastController } from '@ionic/angular';
import { Router } from '@angular/router';

@Component({
  selector: 'app-add-featured',
  templateUrl: './add-featured.component.html',
  styleUrls: ['./add-featured.component.scss'],
  standalone: true,
  imports: [
    CommonModule, FormsModule, IonHeader, IonToolbar, IonTitle,
    IonContent, IonButtons, IonBackButton, IonButton, IonIcon,
    IonList, IonItem, IonLabel, IonInput, IonText, IonToggle,
    IonProgressBar, IonSelect, IonSelectOption
  ]
})
export class AddFeaturedComponent {
  newItem: Partial<InventoryItem> = {
    item_name: '', category: '', supplier_name: '',
    price: 0, quantity: 0, featured_item: 0,
    stock_status: 'Out of stock', special_note: ''
  };

  isLoading = false;

  constructor(
    private inventoryService: InventoryService,
    private navCtrl: NavController,
    private toastController: ToastController,
    private router: Router
  ) {
    addIcons({ saveOutline, closeOutline, addCircleOutline, helpCircleOutline });
  }

  onQuantityChange() {
    const qty = Number(this.newItem.quantity) || 0;
    this.newItem.stock_status = qty > 0 ? 'In stock' : 'Out of stock';
  }

  async saveItem() {
    if (!this.newItem.item_name?.trim() || !this.newItem.category || !this.newItem.supplier_name?.trim()) {
      this.presentToast('Please fill all required fields', 'danger');
      return;
    }

    const itemToAdd = {
      ...this.newItem,
      item_name: this.newItem.item_name.trim(),
      featured_item: this.newItem.featured_item ? 1 : 0,
      stock_status: Number(this.newItem.quantity) > 0 ? 'In stock' : 'Out of stock'
    } as InventoryItem;

    this.isLoading = true;
    this.inventoryService.addItem(itemToAdd).subscribe({
      next: () => {
        this.isLoading = false;
        this.presentToast('Item added successfully!', 'success');
        this.router.navigate(['/tabs/inventory-list']);
      },
      error: () => {
        this.isLoading = false;
        this.presentToast('Failed to add item.', 'danger');
      }
    });
  }

  async presentToast(message: string, color: string) {
    const toast = await this.toastController.create({
      message, duration: 2000, color, position: 'bottom'
    });
    toast.present();
  }

  showHelp() {
    alert("ADD HELP:\n- All fields with * are required.\n- Featured items will be highlighted with a star.\n- IDs are auto-generated by the server.");
  }

  cancel() {
    this.navCtrl.back();
  }
}